packages:
  - "frontend"
  - "backend"
  - "admin-panel"

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "esbuild"
  - "sharp"
  - "unrs-resolver"
  - "vue-demi"
  - "workerd"

minimumReleaseAgeExclude:
  - '@nuxt/ui@4.10.0'
